name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21'

      - run: |
          curl -L https://github.com/golangci/golangci-lint/releases/download/v1.51.2/golangci-lint-1.51.2-linux-amd64.tar.gz \
              | tar --wildcards -xzf - --strip-components 1 "**/golangci-lint"

      - run: ./golangci-lint run -c .golangci.yml -v --timeout=10m

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.6'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install ansible-core

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run tests
        run: |
          make test
